# Generated by Django 3.2 on 2022-01-23 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('priv_message', '0005_auto_20220122_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='date',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='notis',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='notis_to',
        ),
        migrations.AlterField(
            model_name='notifications',
            name='pm',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
