# Generated by Django 3.2 on 2021-12-30 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_post_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
