# Generated by Django 3.2 on 2022-01-01 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_delete_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
    ]
