# Generated by Django 3.2 on 2022-01-07 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Comment',
            new_name='comment',
        ),
    ]
