# Generated by Django 3.2 on 2022-01-08 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0004_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='birth',
            new_name='birthday',
        ),
        migrations.AlterField(
            model_name='users',
            name='picture',
            field=models.ImageField(blank=True, default='profile_images/default_profile.png', upload_to='profile_images'),
        ),
    ]
