# Generated by Django 3.2 on 2022-01-08 11:19

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0005_auto_20220108_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='picture',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
