# Generated by Django 3.2 on 2022-01-10 10:11

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0007_auto_20220109_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='upload',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
