# Generated by Django 3.2 on 2022-01-10 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0009_auto_20220110_1048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='like',
            new_name='likes',
        ),
    ]
